unit TestTaxEvaluatorStrategyController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SalaryEntities, TaxEvaluatorStrategyController,
  InterfaceSalaryEvaluatorController;

type
  // Test methods for class TTaxEvaluatorStrategyController

  TestTTaxEvaluatorStrategyController = class(TTestCase)
  strict private
    FTaxEvaluatorStrategyController: TTaxEvaluatorStrategyController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestEvaluate;
  end;

implementation

procedure TestTTaxEvaluatorStrategyController.SetUp;
begin
  FTaxEvaluatorStrategyController := TTaxEvaluatorStrategyController.Create;
end;

procedure TestTTaxEvaluatorStrategyController.TearDown;
begin
  FTaxEvaluatorStrategyController.Free;
  FTaxEvaluatorStrategyController := nil;
end;

procedure TestTTaxEvaluatorStrategyController.TestEvaluate;
var
  ReturnValue: Boolean;
  p_Salary: TSalary;
  p_Res: Single;
begin
  p_Salary := TSalary.Create;
  p_Salary.FormaOpodatkowania.IdFormy := FORMAOPODATKOWANIA_LINIOWY_INDEX;
  p_Salary.Brutto           := 12300.00;
  p_Salary.Vat              := 1000.00;
  p_Salary.Podatek          := 1000.00;
  p_Salary.ZUS              := 1000.00;
  p_Salary.SkladkaZdrowotna := 1000.00;

  p_Salary.DniRoboczych       := 20;
  p_Salary.DniPrzepracowanych := 15;

  ReturnValue := FTaxEvaluatorStrategyController.Evaluate(p_Salary);

  p_Res := 9314.44;

  CheckEquals(p_Res, p_Salary.DoRozdysponowania);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTTaxEvaluatorStrategyController.Suite);
end.

